server:
  port: 22021

spring:
  datasource:
    url: jdbc:mysql://${db.host}:${db.port:3306}/ssh-connect-db?useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: ${db.username:root}
    password: ${db.password}
  jpa:
    generate-ddl: true