server:
  port: 22022

db:
  host: 127.0.0.1
  port: 3306
  name: ssh-connect-db


spring:
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/${db.name}?useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: '00000000'
  jpa:
    generate-ddl: true